version: '3'

services:
        my_blog_front:
                build:
                        context: .
                        
                image: blog-front:latest

                container_name: myBlogFront
                
                deploy:
                        mode: replicated
                        replicas: 3

                ports:
                       - "80:80"
                       
