version: '3'

services:
  my_blog_front:
    build:
      context: .

    image: blog-front:latest

    container_name: myBlogFront

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "80:80"
                       
