version: '3'

services:
  my_blog_front:
    image: hub.develobeer.blog/blog-front:${TAG}

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "80:80"