version: '3'

services:
        my_blog_front:
                build:
                        context: .
                        
                image: blog-front:latest

                container_name: myBlogFront

                ports:
                       - "80:80"
                       
