version: "3"

services:
        my_blog_front:
                build:
                        context: .
                        dockerfile: ./Dockerfile

                container_name: myBlogFront
                networks:
                        - blog-front

                ports:
                       - "80:80"
                       
